<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

/*
 * todo add aliases and regex
 */
class CountrySeeder extends Seeder
{
    use WithoutModelEvents;

    private array $attributes = [
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'af', 'alpha_3' => 'afg', 'name' => 'Afghanistan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'al', 'alpha_3' => 'alb', 'name' => 'Albania'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'dz', 'alpha_3' => 'dza', 'name' => 'Algeria'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ad', 'alpha_3' => 'and', 'name' => 'Andorra'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ao', 'alpha_3' => 'ago', 'name' => 'Angola'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ag', 'alpha_3' => 'atg', 'name' => 'Antigua and Barbuda'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ar', 'alpha_3' => 'arg', 'name' => 'Argentina'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'am', 'alpha_3' => 'arm', 'name' => 'Armenia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'au', 'alpha_3' => 'aus', 'name' => 'Australia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'at', 'alpha_3' => 'aut', 'name' => 'Austria'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'az', 'alpha_3' => 'aze', 'name' => 'Azerbaijan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bs', 'alpha_3' => 'bhs', 'name' => 'Bahamas'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bh', 'alpha_3' => 'bhr', 'name' => 'Bahrain'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bd', 'alpha_3' => 'bgd', 'name' => 'Bangladesh'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bb', 'alpha_3' => 'brb', 'name' => 'Barbados'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'by', 'alpha_3' => 'blr', 'name' => 'Belarus'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'be', 'alpha_3' => 'bel', 'name' => 'Belgium'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bz', 'alpha_3' => 'blz', 'name' => 'Belize'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bj', 'alpha_3' => 'ben', 'name' => 'Benin'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bt', 'alpha_3' => 'btn', 'name' => 'Bhutan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bo', 'alpha_3' => 'bol', 'name' => 'Bolivia (Plurinational State of]'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ba', 'alpha_3' => 'bih', 'name' => 'Bosnia and Herzegovina'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bw', 'alpha_3' => 'bwa', 'name' => 'Botswana'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'br', 'alpha_3' => 'bra', 'name' => 'Brazil'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bn', 'alpha_3' => 'brn', 'name' => 'Brunei Darussalam'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bg', 'alpha_3' => 'bgr', 'name' => 'Bulgaria'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bf', 'alpha_3' => 'bfa', 'name' => 'Burkina Faso'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'bi', 'alpha_3' => 'bdi', 'name' => 'Burundi'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cv', 'alpha_3' => 'cpv', 'name' => 'Cabo Verde'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'kh', 'alpha_3' => 'khm', 'name' => 'Cambodia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cm', 'alpha_3' => 'cmr', 'name' => 'Cameroon'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ca', 'alpha_3' => 'can', 'name' => 'Canada'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cf', 'alpha_3' => 'caf', 'name' => 'Central African Republic'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'td', 'alpha_3' => 'tcd', 'name' => 'Chad'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cl', 'alpha_3' => 'chl', 'name' => 'Chile'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cn', 'alpha_3' => 'chn', 'name' => 'China'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'co', 'alpha_3' => 'col', 'name' => 'Colombia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'km', 'alpha_3' => 'com', 'name' => 'Comoros'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cg', 'alpha_3' => 'cog', 'name' => 'Congo'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cd', 'alpha_3' => 'cod', 'name' => 'Congo, Democratic Republic of the'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cr', 'alpha_3' => 'cri', 'name' => 'Costa Rica'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ci', 'alpha_3' => 'civ', 'name' => 'Côte d\'Ivoire'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'hr', 'alpha_3' => 'hrv', 'name' => 'Croatia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cu', 'alpha_3' => 'cub', 'name' => 'Cuba'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cy', 'alpha_3' => 'cyp', 'name' => 'Cyprus'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'cz', 'alpha_3' => 'cze', 'name' => 'Czechia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'dk', 'alpha_3' => 'dnk', 'name' => 'Denmark'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'dj', 'alpha_3' => 'dji', 'name' => 'Djibouti'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'dm', 'alpha_3' => 'dma', 'name' => 'Dominica'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'do', 'alpha_3' => 'dom', 'name' => 'Dominican Republic'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ec', 'alpha_3' => 'ecu', 'name' => 'Ecuador'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'eg', 'alpha_3' => 'egy', 'name' => 'Egypt'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sv', 'alpha_3' => 'slv', 'name' => 'El Salvador'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gq', 'alpha_3' => 'gnq', 'name' => 'Equatorial Guinea'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'er', 'alpha_3' => 'eri', 'name' => 'Eritrea'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ee', 'alpha_3' => 'est', 'name' => 'Estonia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sz', 'alpha_3' => 'swz', 'name' => 'Eswatini'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'et', 'alpha_3' => 'eth', 'name' => 'Ethiopia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'fj', 'alpha_3' => 'fji', 'name' => 'Fiji'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'fi', 'alpha_3' => 'fin', 'name' => 'Finland'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'fr', 'alpha_3' => 'fra', 'name' => 'France'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ga', 'alpha_3' => 'gab', 'name' => 'Gabon'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gm', 'alpha_3' => 'gmb', 'name' => 'Gambia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ge', 'alpha_3' => 'geo', 'name' => 'Georgia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'de', 'alpha_3' => 'deu', 'name' => 'Germany'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gh', 'alpha_3' => 'gha', 'name' => 'Ghana'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gr', 'alpha_3' => 'grc', 'name' => 'Greece'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gd', 'alpha_3' => 'grd', 'name' => 'Grenada'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gt', 'alpha_3' => 'gtm', 'name' => 'Guatemala'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gn', 'alpha_3' => 'gin', 'name' => 'Guinea'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gw', 'alpha_3' => 'gnb', 'name' => 'Guinea-Bissau'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gy', 'alpha_3' => 'guy', 'name' => 'Guyana'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ht', 'alpha_3' => 'hti', 'name' => 'Haiti'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'hn', 'alpha_3' => 'hnd', 'name' => 'Honduras'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'hu', 'alpha_3' => 'hun', 'name' => 'Hungary'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'is', 'alpha_3' => 'isl', 'name' => 'Iceland'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'in', 'alpha_3' => 'ind', 'name' => 'India'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'id', 'alpha_3' => 'idn', 'name' => 'Indonesia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ir', 'alpha_3' => 'irn', 'name' => 'Iran (Islamic Republic of]'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'iq', 'alpha_3' => 'irq', 'name' => 'Iraq'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ie', 'alpha_3' => 'irl', 'name' => 'Ireland'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'il', 'alpha_3' => 'isr', 'name' => 'Israel'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'it', 'alpha_3' => 'ita', 'name' => 'Italy'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'jm', 'alpha_3' => 'jam', 'name' => 'Jamaica'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'jp', 'alpha_3' => 'jpn', 'name' => 'Japan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'jo', 'alpha_3' => 'jor', 'name' => 'Jordan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'kz', 'alpha_3' => 'kaz', 'name' => 'Kazakhstan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ke', 'alpha_3' => 'ken', 'name' => 'Kenya'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ki', 'alpha_3' => 'kir', 'name' => 'Kiribati'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regexp', 'alpha_2' => 'kp', 'alpha_3' => 'prk', 'name' => 'Korea (Democratic People\'s Republic of]'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'kr', 'alpha_3' => 'kor', 'name' => 'Korea, Republic of'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'kw', 'alpha_3' => 'kwt', 'name' => 'Kuwait'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'kg', 'alpha_3' => 'kgz', 'name' => 'Kyrgyzstan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'la', 'alpha_3' => 'lao', 'name' => 'Lao People\'s Democratic Republic'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'lv', 'alpha_3' => 'lva', 'name' => 'Latvia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'lb', 'alpha_3' => 'lbn', 'name' => 'Lebanon'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ls', 'alpha_3' => 'lso', 'name' => 'Lesotho'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'lr', 'alpha_3' => 'lbr', 'name' => 'Liberia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ly', 'alpha_3' => 'lby', 'name' => 'Libya'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'li', 'alpha_3' => 'lie', 'name' => 'Liechtenstein'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'lt', 'alpha_3' => 'ltu', 'name' => 'Lithuania'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'lu', 'alpha_3' => 'lux', 'name' => 'Luxembourg'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mg', 'alpha_3' => 'mdg', 'name' => 'Madagascar'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mw', 'alpha_3' => 'mwi', 'name' => 'Malawi'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'my', 'alpha_3' => 'mys', 'name' => 'Malaysia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mv', 'alpha_3' => 'mdv', 'name' => 'Maldives'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ml', 'alpha_3' => 'mli', 'name' => 'Mali'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mt', 'alpha_3' => 'mlt', 'name' => 'Malta'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mh', 'alpha_3' => 'mhl', 'name' => 'Marshall Islands'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mr', 'alpha_3' => 'mrt', 'name' => 'Mauritania'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mu', 'alpha_3' => 'mus', 'name' => 'Mauritius'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mx', 'alpha_3' => 'mex', 'name' => 'Mexico'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'fm', 'alpha_3' => 'fsm', 'name' => 'Micronesia (Federated States of]'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'md', 'alpha_3' => 'mda', 'name' => 'Moldova, Republic of'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mc', 'alpha_3' => 'mco', 'name' => 'Monaco'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mn', 'alpha_3' => 'mng', 'name' => 'Mongolia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'me', 'alpha_3' => 'mne', 'name' => 'Montenegro'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ma', 'alpha_3' => 'mar', 'name' => 'Morocco'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mz', 'alpha_3' => 'moz', 'name' => 'Mozambique'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mm', 'alpha_3' => 'mmr', 'name' => 'Myanmar'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'na', 'alpha_3' => 'nam', 'name' => 'Namibia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'nr', 'alpha_3' => 'nru', 'name' => 'Nauru'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'np', 'alpha_3' => 'npl', 'name' => 'Nepal'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'nl', 'alpha_3' => 'nld', 'name' => 'Netherlands'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'nz', 'alpha_3' => 'nzl', 'name' => 'New Zealand'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ni', 'alpha_3' => 'nic', 'name' => 'Nicaragua'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ne', 'alpha_3' => 'ner', 'name' => 'Niger'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ng', 'alpha_3' => 'nga', 'name' => 'Nigeria'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'mk', 'alpha_3' => 'mkd', 'name' => 'North Macedonia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'no', 'alpha_3' => 'nor', 'name' => 'Norway'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'om', 'alpha_3' => 'omn', 'name' => 'Oman'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'pk', 'alpha_3' => 'pak', 'name' => 'Pakistan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'pw', 'alpha_3' => 'plw', 'name' => 'Palau'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'pa', 'alpha_3' => 'pan', 'name' => 'Panama'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'pg', 'alpha_3' => 'png', 'name' => 'Papua New Guinea'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'py', 'alpha_3' => 'pry', 'name' => 'Paraguay'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'pe', 'alpha_3' => 'per', 'name' => 'Peru'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ph', 'alpha_3' => 'phl', 'name' => 'Philippines'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'pl', 'alpha_3' => 'pol', 'name' => 'Poland'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'pt', 'alpha_3' => 'prt', 'name' => 'Portugal'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'qa', 'alpha_3' => 'qat', 'name' => 'Qatar'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ro', 'alpha_3' => 'rou', 'name' => 'Romania'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ru', 'alpha_3' => 'rus', 'name' => 'Russian Federation'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'rw', 'alpha_3' => 'rwa', 'name' => 'Rwanda'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'kn', 'alpha_3' => 'kna', 'name' => 'Saint Kitts and Nevis'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'lc', 'alpha_3' => 'lca', 'name' => 'Saint Lucia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'vc', 'alpha_3' => 'vct', 'name' => 'Saint Vincent and the Grenadines'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ws', 'alpha_3' => 'wsm', 'name' => 'Samoa'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sm', 'alpha_3' => 'smr', 'name' => 'San Marino'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'st', 'alpha_3' => 'stp', 'name' => 'Sao Tome and Principe'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sa', 'alpha_3' => 'sau', 'name' => 'Saudi Arabia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sn', 'alpha_3' => 'sen', 'name' => 'Senegal'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'rs', 'alpha_3' => 'srb', 'name' => 'Serbia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sc', 'alpha_3' => 'syc', 'name' => 'Seychelles'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sl', 'alpha_3' => 'sle', 'name' => 'Sierra Leone'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sg', 'alpha_3' => 'sgp', 'name' => 'Singapore'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sk', 'alpha_3' => 'svk', 'name' => 'Slovakia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'si', 'alpha_3' => 'svn', 'name' => 'Slovenia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sb', 'alpha_3' => 'slb', 'name' => 'Solomon Islands'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'so', 'alpha_3' => 'som', 'name' => 'Somalia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'za', 'alpha_3' => 'zaf', 'name' => 'South Africa'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ss', 'alpha_3' => 'ssd', 'name' => 'South Sudan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'es', 'alpha_3' => 'esp', 'name' => 'Spain'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'lk', 'alpha_3' => 'lka', 'name' => 'Sri Lanka'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sd', 'alpha_3' => 'sdn', 'name' => 'Sudan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sr', 'alpha_3' => 'sur', 'name' => 'Suriname'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'se', 'alpha_3' => 'swe', 'name' => 'Sweden'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ch', 'alpha_3' => 'che', 'name' => 'Switzerland'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'sy', 'alpha_3' => 'syr', 'name' => 'Syrian Arab Republic'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tj', 'alpha_3' => 'tjk', 'name' => 'Tajikistan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tz', 'alpha_3' => 'tza', 'name' => 'Tanzania, United Republic of'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'th', 'alpha_3' => 'tha', 'name' => 'Thailand'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tl', 'alpha_3' => 'tls', 'name' => 'Timor-Leste'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tg', 'alpha_3' => 'tgo', 'name' => 'Togo'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'to', 'alpha_3' => 'ton', 'name' => 'Tonga'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tt', 'alpha_3' => 'tto', 'name' => 'Trinidad and Tobago'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tn', 'alpha_3' => 'tun', 'name' => 'Tunisia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tr', 'alpha_3' => 'tur', 'name' => 'Türkiye'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tm', 'alpha_3' => 'tkm', 'name' => 'Turkmenistan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'tv', 'alpha_3' => 'tuv', 'name' => 'Tuvalu'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ug', 'alpha_3' => 'uga', 'name' => 'Uganda'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ua', 'alpha_3' => 'ukr', 'name' => 'Ukraine'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ae', 'alpha_3' => 'are', 'name' => 'United Arab Emirates'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'gb', 'alpha_3' => 'gbr', 'name' => 'United Kingdom of Great Britain and Northern Ireland'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'us', 'alpha_3' => 'usa', 'name' => 'United States of America'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'uy', 'alpha_3' => 'ury', 'name' => 'Uruguay'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'uz', 'alpha_3' => 'uzb', 'name' => 'Uzbekistan'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'vu', 'alpha_3' => 'vut', 'name' => 'Vanuatu'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 've', 'alpha_3' => 'ven', 'name' => 'Venezuela (Bolivarian Republic of]'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'vn', 'alpha_3' => 'vnm', 'name' => 'Viet Nam'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'ye', 'alpha_3' => 'yem', 'name' => 'Yemen'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'zm', 'alpha_3' => 'zmb', 'name' => 'Zambia'],
        ['aliases' => ['first aliases', 'second aliases'], 'zip_code_regex' => 'zip code regex', 'alpha_2' => 'zw', 'alpha_3' => 'zwe', 'name' => 'Zimbabwe'],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->attributes as $attribute) {
            Country::create($attribute);
        }
    }
}
